# Generated by Django 2.1 on 2018-08-22 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='类别'),
        ),
    ]
