# Generated by Django 2.1 on 2018-08-22 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='商品数量')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单商品详情',
                'verbose_name_plural': '订单商品详情',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(max_length=50, verbose_name='第三方流水号')),
                ('pay_status', models.CharField(choices=[('sucess', '成功'), ('cancel', '取消'), ('daizhifu', '待支付')], default='daizhifu', max_length=10, verbose_name='支付状态')),
                ('post_script', models.CharField(max_length=200, verbose_name='支付留言')),
                ('order_mount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='订单金额')),
                ('pay_time', models.DateTimeField()),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('signer_name', models.CharField(default='', max_length=100, verbose_name='签收人')),
                ('singer_mobile', models.CharField(default='', max_length=11, verbose_name='签收人电话')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_nums', models.IntegerField(default=1, verbose_name='商品数量')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
